### ISSUE TITLE
Soldermask issue

### ISSUE THREAD

**Issue by G-Pereira** [sphawes/index#107]
Soldermask clearance and solder mask minimum width should be set to zero in **EVERY** board. This improves solder quality for LQFP chips, otherwise solder bridges can be frequent.
Current soldermask:
![image](https://user-images.githubusercontent.com/15521303/103685429-1ff00380-4f85-11eb-9cf8-717efb047da2.png)
How it should be:
![image](https://user-images.githubusercontent.com/15521303/103685454-27171180-4f85-11eb-9265-363f56531f62.png)

**Comment by wilhelmzeuschner** [comment]
What I believe to be the case is, that Stephen probably took this value from JLCPCB's Website: https://jlcpcb.com/capabilities/Capabilities
![image](https://user-images.githubusercontent.com/37621765/103686241-cd1b4980-4f8e-11eb-8028-e144e81f8a35.png)

That being said, I too have always used a 0 in that setting for all of my orders (from JLCPCB) and have never experienced any issues with low-pitch packages.

**Comment by bholmes451** [comment]
The other very important factor to consider is the Stencil thickness for these parts. If you are getting bridges you may need to use a thinner stencil. For a couple of my designs simply going from the default .12mm thick stencil to a .10mm stencil eliminated the bridging.

**Comment by G-Pereira** [comment]
@wilhelmzeuschner that's unlikely since the set values are KiCAD defaults. KiCAD recommends setting this value to zero and the fab does the best he can.
@bholmes451 nice to know! The paste clearance and minimum width are both set to zero so this issue doesn't change the paste layer

**Comment by wilhelmzeuschner** [comment]
@G-Pereira weird, when I start a new blank project these values default to 0. Maybe KiCAD remembers the last setting, although that doesn't seem to make much sense. Why would the default value be different from the recommended one anyways?

But that's not really the point, as said earlier, I completely agree with you, that this should probably be set to 0 in this case. :)

**Comment by G-Pereira** [comment]
@wilhelmzeuschner That happens to me as well when I start a new project on my computer. It is always set to zero because I've changed it once to zero
