### ISSUE TITLE
Different versions of FDM-0014-00_down-camera-mount

### ISSUE THREAD

**Issue by JudgeBeeb** [sphawes/index#108]
The version of FDM-0014-00_down-camera-mount in assembly.FCStd (and the STL that is generated from assembly.FCStd) is different from the. single FDM-0014-00_down-camera-mount.FCStd file. The version in assembly.FCStd has mount holes for the camera module which are too small to accept M2.5 screws.

**Comment by G-Pereira** [comment]
Is there any way to use links on the assembly instead of copies? That way the assembly would be always updated. That's important because the STL files are generated from the assembly!
