### ISSUE TITLE
[Mobo] Add LEDs for Mosfet Outputs

### ISSUE THREAD

**Issue by wilhelmzeuschner** [sphawes/index#118]
This has already been discussed in some other issues but it seems that it hasn't been added (yet).
It would be awesome to have the ability to see the output status immediately when debugging.

This has been referenced in #69 but it wasn't what the issue was about.
And @G-Pereira mentioned it in [PR78](https://github.com/sphawes/index/pull/78)

**Comment by martinbogo** [comment]
I'm all for this -- make sure the LED's don't draw significant current when
connected, and that the LED is in parallel so that you can depop the LED (
or it's resistor ) to disable the feature.

**Comment by wilhelmzeuschner** [comment]
@martinbogo or even add a small solder jumper that is NO, making enabling / disabling it faster and cleaner :)

**Comment by G-Pereira** [comment]
Added!
