### ISSUE TITLE
[Feeder] Rollback Feeder RS485

### ISSUE THREAD

**Issue by daveismith** [sphawes/index#123]
In the feeder BOM that's included for auto-generation for JLCPCB I put in the part number for the MAX3078E as @Jnesselr has indicated that part has hot swap capabilities. I plan to test on my own build, but realized I shouldn't have committed it into the branch until that testing is complete.

**Comment by G-Pereira** [comment]
Don't worry, the previous one is barely tested as well in its full extent. Bugs arising from this IC will be common to both transceivers
