### ISSUE TITLE
GitHub issues templates

### ISSUE THREAD

**Issue by G-Pereira** [sphawes/index#129]
Design templates for issues for Mono and feeders in order to help people better explain the bugs/suggestions and also help issue assignment to each collaborator.

**Comment by daveismith** [comment]
I would suggest a template for each of the PCBs that will fill in the appropriate labels. Also it should ask PCB version, if it's a feature request or bug. 

For bugs, it should ask for a screenshot of either the schematic or pcb highlighting the issue. Other material to demonstrate the issue would be good too (eg, scope traces, logic captures, spice simulations, etc)

For a new request/improvement, it should describe the changes being requested but also the intent for the change (ie, what does it improve or enable). Ideally any specific parts that are being requested / suggested should have a link to the datasheet.
