### ISSUE TITLE
Front feeder rail too far -Y axis. Camera cannot see pick location.

### ISSUE THREAD

**Issue by sphawes** [sphawes/index#13]
The front feeder rail is too far in the -Y axis (towards the user). Shifting it back 20mm will allow the nozzle and the camera to easily see the pick area. This will also likely allow a wider range of other feeder designs to work with pre-pick vision.

**Comment by Frzoen** [comment]
What about shifting feeders in X-axis apart to accommodate space for camera between them? Then camera could be even closer in Y axis

**Comment by raouldeheer** [comment]
Wassen't this issue fixed in cad _v1.1.0_?

**Comment by sphawes** [comment]
v1.1.0 shifted the feeder rail forward by 20mm, but it has yet to be confirmed that the camera can see the feeder output. this depends on 1) the feeder design, which is still in flux, and 2) new camera mount for the head, which is being designed. once it's confirmed it's visible ill close this up.

**Comment by daveismith** [comment]
@sphawes is this still relevant with the latest feeder and free cad designs?

**Comment by G-Pereira** [comment]
Yes @daveismith this was fixed!
