### ISSUE TITLE
No assembly instructions.

### ISSUE THREAD

**Issue by Frzoen** [sphawes/index#14]
There is no assembly instruction for the mechanical part of project.
I can help with that using [Overlaf](https://www.overleaf.com/)

**Comment by arturo182** [comment]
I'm currently in the process of printing the 3d printed parts and should be receiving most of the mechanical in the coming week. I will try to take lots of photos and document my assembly attempt (hopefully aided by @sphawes), we could use that for the instructions later :)

**Comment by arturo182** [comment]
You can see my Twitter thread (https://twitter.com/arturo182/status/1268657313696698370) for some progress photos, I also provided the photos to Stephen if he wants to use them in the instructions.

**Comment by Frzoen** [comment]
That would be great. As from my side i could add exploded views from cad. Unfortunately i didn't took any picture during assembly...

**Comment by LoneWalkerWolf** [comment]
I too am going to she documenting my assembly of the Index. I will probably upload a .zip file with all the pictures I took. I am also planning to record a video of my assembling the machine.

**Comment by daveismith** [comment]
We've got a google doc with assembly instructions currently. It's in the code lab format for now but that's under discussion as a few other formats have been suggested. Once content is complete we will convert to markdown and add to the repo with the intent to generate a site which could be hosted using GitHub pages.

**Comment by meutzitzu** [comment]
one can consider using TechDrawWB and ExplodedAssemblyWB in FreeCAD to generate instructions.

**Comment by G-Pereira** [comment]
> one can consider using TechDrawWB and ExplodedAssemblyWB in FreeCAD to generate instruction illustrations

That is in our plans as well as animated assemblies using FreeCAD rendering capabilities using Cycles (Blender) integration!

**Comment by G-Pereira** [comment]
Thanks @Frzoen ! The assembly instructions are now present in the assembly-guide branch
