### ISSUE TITLE
[CAD] - Y endstop not hitting the gantry properly

### ISSUE THREAD

**Issue by wilhelmzeuschner** [sphawes/index#152]
# Description
The Y endstop switch does not hit the gantry (FDM-0005-02_y-gantry) very well. To fix this, I glued a small piece of plastic onto it.
To fix this issue, the limit switch would need to be moved further "into / (to the right on the images, see below)" the front left leg (FDM-0001-01_front-left-leg), so that the switch makes better contact with the gantry . An alternative could be to design part of the gantry differently, although this could make the part harder to print, depending on the changes. Maybe a special, larger belt clamp (FDM-0025-00_belt-clamp_Body_001) could be printed but this would not be ideal either, since this part may need adjusting from time to time and would thus change the exact coordinates when homing. Also this would introduce yet another special part.

## Here are some photos:

**Illustration of the issue:**
Green: makeshift extension
Red: edge of the printed part
Yellow: limit switch contact area
![IMG_20210208_202711 - Copy](https://user-images.githubusercontent.com/37621765/107422725-af0bb080-6b1b-11eb-98ec-79abaca74c7e.jpg)

**Same image, but unedited**
![IMG_20210208_202711](https://user-images.githubusercontent.com/37621765/107422727-afa44700-6b1b-11eb-8308-5c77bb028904.jpg)

**Other angles:**
![IMG_20210208_202659](https://user-images.githubusercontent.com/37621765/107422714-ac10c000-6b1b-11eb-9ece-1cdc176664b6.jpg)
![IMG_20210208_202716](https://user-images.githubusercontent.com/37621765/107422729-afa44700-6b1b-11eb-8b4e-077228b8ce12.jpg)

**Comment by JudgeBeeb** [comment]
This is already a known issue: https://github.com/sphawes/index/issues/76

**Comment by G-Pereira** [comment]
Hey! Looks like you are misusing the belt clamps. Look here:
![IMG_20210223_125602](https://user-images.githubusercontent.com/15521303/108846538-98169500-75d6-11eb-984f-54558ac8f63e.jpg)
![IMG_20210223_125530](https://user-images.githubusercontent.com/15521303/108846551-9cdb4900-75d6-11eb-847e-992a90d4290c.jpg)

**Comment by wilhelmzeuschner** [comment]
The problem was my use of the older design version of the clamps, which were round and also the fact, that the limit switch was angled slightly towards the gantry. This way, it never hit either of the parts reliably.
