### ISSUE TITLE
Separate Assembly instructions in smaller sections

### ISSUE THREAD

**Issue by G-Pereira** [sphawes/index#154]

**Comment by daveismith** [comment]
I would suggest:

- Separate Guides:
    - Flashing MOBO
    - Configuring OpenPNP
    - Running A Job
- Separate Sections for each "page" of the instructions.

Some of this will come down to the output format we choose.

**Comment by G-Pereira** [comment]
I agree with that separation however for the "Running a job" I would make it only some notes and then link OpenPnP wiki for it. We don't want to maintain a guide for a 3rd party software.

**Comment by daveismith** [comment]
This has been done with the documentation that's now hosted at https://docs.index-machines.com
