### ISSUE TITLE
[CAD] - Feeder CAD blocks VCNT2020 option

### ISSUE THREAD

**Issue by daveismith** [sphawes/index#160]
The current guide-left part of the CAD doesn't allow for the PCB to be stuffed with the VCNT2020 sensor. 

![Screen Shot 2021-02-17 at 19 14 18](https://user-images.githubusercontent.com/1734595/108285436-14cbee00-7155-11eb-8f30-10c8e670d7e8.png)

Suggestion would be to add a small cutout to allow those parts to be populated.

**Comment by G-Pereira** [comment]
VCNT2020 has been deprecated
