### ISSUE TITLE
[MOBO] - Analog supply isn't separated from digital supply

### ISSUE THREAD

**Issue by wilhelmzeuschner** [sphawes/index#165]
Should add a ferrite filter or something, this was already fixed at some point?
![image](https://user-images.githubusercontent.com/37621765/108634084-3d672700-7478-11eb-9675-cdfea01bba0e.png)

**Comment by G-Pereira** [comment]
We are not using the MCU ADC and will probably never will due to the complexity it would be to add it to marlin. We are using an external ADC instead. That circuit will have this filter.
