### ISSUE TITLE
[MOBO] - Reduce amount of different BOM parts

### ISSUE THREAD

**Issue by wilhelmzeuschner** [sphawes/index#166]
Currently many values of capacitors / resistors are used. Most of these can be changed to one common  value.
This makes the BOM neater, greatly increases the ease of assembly by hand or PNPing since fewer part feeders are necessary.

Here are some of these parts:
4.7u: replace with 1x or 2x 2.2u
1u: (used for analog decoupling, but 2.2u should work just as good)
10u tantalum: replace with a combination of "a few" 2.2u ceramics (and 10u electrolytic? probably not needed)
10u ceramics for FE1.1: replace with smaller values (2.2u)? This value might be critical though! -> use 10u electrolytic instead of 10u ceramic to remove the ceramic from the BOM?
![image](https://user-images.githubusercontent.com/37621765/108634217-e31a9600-7478-11eb-9096-ca20a45364af.png)

1k resistors: can be completely replaced by 10k, no critical values.
470R: probably to be removed anyhow
100k: replace with 10k (used to pull down mosfet gate)
![image](https://user-images.githubusercontent.com/37621765/108633906-30960380-7477-11eb-9a72-218bdbfa9605.png)
560R: replace with 120R (would increase the max. current drawn from the IO when _switching_ the MOSFET (27.5mA vs 6mA, probably fine though.)
4.7k: I²C pull up, 10k should work

**Comment by G-Pereira** [comment]
Thanks! Most of these suggestions were applied and the number of different value resistors was greatly reduced
