### ISSUE TITLE
Add termination resistor on Feeder Floor

### ISSUE THREAD

**Issue by G-Pereira** [sphawes/index#168]
There should be a termination resistor at the start and end of the RS-485 bus (Mobo and last feeder floor)

**Comment by daveismith** [comment]
@G-Pereira - I think that this is already in place unless I've misunderstood the following schematic.

![image](https://user-images.githubusercontent.com/1734595/109092450-8cb18f80-76e4-11eb-9c6d-cb0d66960864.png)

**Comment by G-Pereira** [comment]
My bad, I assumed there wasn't since the value for it on the mobo was 220 Ohms. It should be around 120 Ohm.
Like we've discussed in Discord we should study the wire impedance to better tune this resistor value.

**Comment by daveismith** [comment]
Fixed in #197
