### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [sphawes/index#2]
Cool project!

I see at least some of this repository has a license, but the root is missing a LICENSE file and the README does not mention anything about the license.  Without a license the default is copyright.

Ploopy_feeder is CERN Open Hardware Licence v1.2.  firmware_marlin is GPL-3.0.  What should the rest be licensed under?  I would suggest GPL-3.0.

**Comment by sphawes** [comment]
Thanks! And thanks for the note! Just added GPL-3.0.

**Comment by TechnologyClassroom** [comment]
@sphawes Great!  You should also add the link to the video and doc from reddit.  Seeing it in action really helps people understand what it does.
