### ISSUE TITLE
Rename rollerSpacer_x6.stl

### ISSUE THREAD

**Issue by Fanfwe** [sphawes/index#21]
Unless I missed something, it needs to be printed 8 times, not 6.
4 pcs for Y carriages (2 pcs each)
2 pcs for the X carriage Front
2 pcs for the X carriage Back

**Comment by arturo182** [comment]
Correct!

**Comment by G-Pereira** [comment]
Thanks @Fanfwe ! This is now clear on our assembly guide present in the assembly-guide branch.
