### ISSUE TITLE
Is there pc software to control the machine?

### ISSUE THREAD

**Issue by musarac** [sphawes/index#220]
Thank you so much for your work.Is there pc software to control the machine?

**Comment by daveismith** [comment]
Yes, it uses the OpenPNP software available at [https://openpnp.org](https://docs.index-machines.com). We're still relatively early in the process of documenting how all of this works together. Please see the wiki for information about contributing, join the discord for discussion and check out the start of our documentation at [https://docs.index-machines.com](https://docs.index-machines.com).
