### ISSUE TITLE
[Assembly Guide] - 

### ISSUE THREAD

**Issue by Gruftgrabbler** [sphawes/index#222]
In the assembly guide for the [x-gantry](https://docs.index-machines.com/docs/mechanical-assembly/x-gantry/) instruction nr 22 tells you to use an M5x45 to connect the GT2-Idler and the Z-Axis-Roller-Spacer to the gantry. 

Doing so will result in the problem that you can not mount the camera later on. Instead you **have to use a M5x30** 
to make enough space for the camera holder part.

Down below you can see that with the shorter screw it fits perfectly

![z-gantry assembly](https://user-images.githubusercontent.com/24829851/111773084-f79e5280-88ad-11eb-99f7-01238fea69e1.jpeg)
![m5x30 screw](https://user-images.githubusercontent.com/24829851/111773087-f8cf7f80-88ad-11eb-9ec5-3d2bd8220077.jpeg)

**Comment by daveismith** [comment]
Updated.
