### ISSUE TITLE
[FEATURE REQUEST] Create a glossary of key terms

### ISSUE THREAD

**Issue by darigovresearch** [sphawes/index#226]
Although this project is definitely an advanced one, thought it would be helpful for new joiners to have a glossary in a .md file or the like so everyone can have an even footing on what some technical terms mean or what certain acronyms stand for.

Many other open source projects do something similar when they start generating their documentation for the project

**Comment by darigovresearch** [comment]
Pull request #239 would resolve this issue

**Comment by daveismith** [comment]
The glossary has been started and is available at [https://docs.index-machines.com/docs/reference/glossary/](https://docs.index-machines.com/docs/reference/glossary/)
