### ISSUE TITLE
[BUG] "Edit this page" feature in docs links to 404 page

### ISSUE THREAD

**Issue by darigovresearch** [sphawes/index#227]
The `Edit this page` button in the docs links to a URL/file which does not exist

Feel free to test this directly from the URL to replicate the issue - https://docs.index-machines.com/docs/

Would do a pull request but this docs system is new to us

**Comment by daveismith** [comment]
This should now be resolved.

**Comment by G-Pereira** [comment]
@darigovresearch When you can pease confirm this since you are an outside contributor.

**Comment by darigovresearch** [comment]
@G-Pereira & @daveismith Yes now I think it redirects to a valid page, thanks for the help!

https://github.com/sphawes/index/edit/assembly-guide/doc/content/en/docs/_index.md

![image](https://user-images.githubusercontent.com/30328618/112722355-eafaa980-8f00-11eb-908e-46feb6fb513c.png)
