### ISSUE TITLE
[MOBO] - Two AUX Ports

### ISSUE THREAD

**Issue by sphawes** [sphawes/index#232]
**Motherboard Revision:** REV03

**Enhancement Description:**
- Switch back to having two auxiliary ports on the mobo
- Each port should have 12/24v, 5V, GND, I2C, and at least 4 GPIO, with at least one of them configurable as an ADC, and at least one configurable as PWM.
- Both ports should have as close to an identical pinout as possible, using an IDC connector.

**Comment by G-Pereira** [comment]
Following our conversation yesterday about the 5V rail I suggest not exposing the 5V rail on the AUX port because if people choose to wire small motors to it it can or cannot be an issue. So to avoid that we would need to spec that port which we would need to absolutely guarantee.
