### ISSUE TITLE
[BUG] References to RING in feeder page

### ISSUE THREAD

**Issue by darigovresearch** [sphawes/index#240]
It appears that the readme for the feeder contains references to RING. After watching the [development playlist](https://www.youtube.com/playlist?list=PLIeJXmcg1baLBz3x0nCDqkYpKs2IWGHk4) our understanding was that RING was deprecated over using RS-485.

Should this be updated or were we mistaken?

Happy to make a pull request to resolve if this should be switched out!

Page in question - https://github.com/sphawes/index/tree/master/feeder

**Comment by cad435** [comment]
yes, that is indeed an error...

@daveismith might be the person to change this or approve a pull request regarding this :)

**Comment by darigovresearch** [comment]
Thanks @cad435 for the guidance, will put in a pull request now!

**Comment by darigovresearch** [comment]
Merging pull request #257 would resolve this issue
