### ISSUE TITLE
[FEEDER] Soldermask Issues on Feeder Mobo (Soldermask Clearance)

### ISSUE THREAD

**Issue by dfancan** [sphawes/index#253]
**Feeder Revision:** REV05

**Issue Description:**
The soldermask around the pins of the STM32 and DRV8833 is missing, presumably due to setting the soldermask clearance to a non-zero value in the KiCad board file. Issue #107 describes and fixes a similar issue, but only on the main Index mobo rev03.
Issue can be seen in the current board rendering:

![](https://cdn.discordapp.com/attachments/739250421893300264/826171695533916212/2CB2F713-FB96-4535-AEB8-DD13EE05EF10.jpeg)

**Suggested Fix:**
Consider changing the soldermask clearance and min. width to 0mm, the fix implemented for the index mobo as seen in #107 .

**Comment by daveismith** [comment]
Resolved by PR #264
