### ISSUE TITLE
[FEEDER] - Serial Bootload Improvements

### ISSUE THREAD

**Issue by daveismith** [sphawes/index#266]
**Feeder Revision:** REV05-b277362

**Enhancement Description:** There is a header for serial located on the bottom edge of the mobo which brings out the RX & TX pins to a 0.1" header which a user can connect to a serial converter for debug. This is attached to the primary UART port of the STM32 and is capable of bootloading, but the board doesn't make this as easy as possible. I would suggest the following changes.

1. Add a button to BOOT0 which when pressed will connect BOOT0 to +3V3.
2. Default the BOOT1 jumpter to GND and enable it to be switched to +3V3 via a trace cut and solder blob.

Making these changes will allow the user to program using any USB to Serial conversion tool (possibly even including a sketch on the mobo)

**Comment by G-Pereira** [comment]
Done!
