### ISSUE TITLE
Right Y axis gantry add adjusters to tension lower roller bearings

### ISSUE THREAD

**Issue by bwattendorf** [sphawes/index#28]
I added 2- 3MM nut slots and holes so 2 screws can be threaded up so the lower roller bearing bolts can be pushed up so they will become tight against the rail and not fall down. 
[right y axis gantry.zip](https://github.com/sphawes/index/files/4880986/right.y.axis.gantry.zip)

**Comment by G-Pereira** [comment]
Thanks @bwattendorf ! This has been added to the current design!
