### ISSUE TITLE
Add lower roller bearing adjusters to left Y axis gantry and also cable chain nut cutouts and bolt thru holes

### ISSUE THREAD

**Issue by bwattendorf** [sphawes/index#29]
Add lower roller bearing adjusters to left Y axis gantry and also cable chain nut cutouts and bolt thru holes.
[lefty axis gantry.zip](https://github.com/sphawes/index/files/4881008/lefty.axis.gantry.zip)

**Comment by G-Pereira** [comment]
Thanks @bwattendorf ! This has been added.
