### ISSUE TITLE
cable chain end for left Y axis and also cable chain files

### ISSUE THREAD

**Issue by bwattendorf** [sphawes/index#30]
The cable chain files are from thingiverse files#11978  ,2951196. WARNING I DID NOT CHECK THE LICENSE FOR THESE PARTS. (so I don't know what it is Sorry). The end mount I created form the STL file. I am still working on the other end for the legs and also the mods for the front and back legs. (I plan on doing both options since my electronics is on the back and yours is on the front. 
[cable chain and ends.zip](https://github.com/sphawes/index/files/4881049/cable.chain.and.ends.zip)
 
Note: cable and chain file 11978 license cc-sa
          print in place file 2951196 Creative Commons - Attribution - Share Alike license.

**Comment by G-Pereira** [comment]
Hi! As the time passed by the choice of cable chains were disregarded in favor of umbilical pipes.
This is now obsolete
