### ISSUE TITLE
[CAD] - Suggestion to improve X gantry front (increase frontal face by 2mm)

### ISSUE THREAD

**Issue by Arthur-Silveira** [sphawes/index#36]
I suggest, to add extra 2 mm on the frontal face of the front X gantry.

The M5x45 screw I've used to hold the rollers have a 5mm lenght head, and some of the head remains exxposed, and will interfere with the linear rail (see pictures).
![image](https://user-images.githubusercontent.com/66083860/89475960-c5494600-d75f-11ea-9aac-109c58720f07.png)
![image](https://user-images.githubusercontent.com/66083860/89475979-cf6b4480-d75f-11ea-8a35-9bf15b736627.png)
![image](https://user-images.githubusercontent.com/66083860/89476001-e6119b80-d75f-11ea-9257-babd4614c3c4.png)

The head top is 1.35 mm above the surface. Those extra 2 mm in the frontal face would completely cover the screw.
![image](https://user-images.githubusercontent.com/66083860/89476079-1eb17500-d760-11ea-8578-7f850c0ffadc.png)

There is 3.8mm of exposed thread in the back nut (I'm using a simple nut). I know that the nylon lock nut will be a bit longer, but I think it isstill enough to spare for increasing to the front face depth.
![image](https://user-images.githubusercontent.com/66083860/89476237-8d8ece00-d760-11ea-8359-33e9979809df.png)

This is a suggestion. If not accepted, maybe adding a warning on the BOM to use M5x45 screws with head length smaller than 3.6 mm length to avoid this issue.

**Comment by OJFord** [comment]
5mm head height is per ISO4762 according to https://www.engineersedge.com/iso_socket_head_screw.htm

**Comment by LoneWalkerWolf** [comment]
To those who are having the same problem:

I have made the changes to this STL File, please use this to reprint your x-gantry-front. 
https://drive.google.com/file/d/1r3FPwXkL4W2Xfw1klLjvMGTdvRtRaKHC/view?usp=sharing

Thanks.

**Comment by G-Pereira** [comment]
This has been incorporated to the project! Nice work!
