### ISSUE TITLE
Missing STL's

### ISSUE THREAD

**Issue by Frzoen** [sphawes/index#4]
Hi guys!
Great job with opening files for this project.

I've spotted missing STL's for :
- X Carriage Front
- X Carriage Back
- Z Carriage
- Roller Spacer

And also names in BOM not always correlate to those in STL folder.

Cheers!

**Comment by NightSkySK** [comment]
I've created pull request to fix on those items:
- added missing stl's
- fixed file names to match BOM list
- rename stl folder name to mark from which version of .step file it was extracted
