### ISSUE TITLE
KiCad Sch & Board to PDF

### ISSUE THREAD

**Issue by paloky** [sphawes/index#43]
Hi Stephen.
Can you include in this repository all KiCad documents in PDF.

It's better for view more fast. (And if don't working with KiCad)   ;-)

Thank a lot.

**Comment by LoneWalkerWolf** [comment]
@paloky Here you go. **Please do however note, that this was the motherboard (as of 1/11/2020).** For future reference, please download KiCad for your convenience. (https://kicad.org/)
[moboPDF.zip](https://github.com/sphawes/index/files/5470998/moboPDF.zip)

**Comment by G-Pereira** [comment]
It would be nice to use [KiBot](https://github.com/INTI-CMNB/KiBot)!

**Comment by daveismith** [comment]
I'm working on this with github actions and KiBot. I'm planning to output:

- ibom format
- csv bom
- html bom
- schematic
- pcb layer pdf (one layer per page, coper first, then silk)
- gerbers (compatible with PCBWay, JLCPCB, DirtyPCB, OSHPark & Aisler)
- drill file
- board top render
- board bottom render
- pick and place file
- JLCPCB compatible BOM (LCSC Part Numbers included)
- JLCPCB CPL file
- Step File

**Comment by daveismith** [comment]
This has been completed in the feeder-rev05 branch with #114 but still needs to be done for the mobo-rev03 branch.

Take a look for an exports directory under each board directory.

**Comment by daveismith** [comment]
This is supported in both the mobo-rev03 and feeder-rev05 branches. Look for an export folder inside the folder containing the schematic and board file.
