### ISSUE TITLE
[CAD] - Z Axis Endstop for OpenPnP alignment. 

### ISSUE THREAD

**Issue by LoneWalkerWolf** [sphawes/index#48]
After trying to get OpenPnP to accurately zero the Z axis, I think it might be necessary to add an extra endstop on the axis. I have designed a quick mount for one (attached below) and this has proven to work on my machine. _(please bear in mind I am still using a RAMPS 1.4 board)_

![render](https://user-images.githubusercontent.com/63847434/97807915-74ac9080-1c5b-11eb-86e5-2b94baa79899.PNG)
![render2](https://user-images.githubusercontent.com/63847434/97807982-cd7c2900-1c5b-11eb-8d3f-86270babc186.PNG)

Here are the files: [z-axis-endstop.zip](https://github.com/sphawes/index/files/5471252/z-axis-endstop.zip)

Cheers.

**Comment by daveismith** [comment]
The latest free cad designs have this in place at the top right of the Z axis part. Is this sufficient to close the ticket?

**Comment by G-Pereira** [comment]
Closing this since it is indeed in place and no answer from the author
