### ISSUE TITLE
Switch film tension and tape detection switches to Hall Effect Sensor

### ISSUE THREAD

**Issue by sphawes** [sphawes/index#50]
The [current switches](https://lcsc.com/product-detail/Microswitches_Korean-Hroparts-Elec-K5-1624SA-01_C128966.html) on the REV003 feeders that detect film tension and tape presence are limit switches with a lifetime rating of 100,000 cycles. 

We should switch these out for a hall effect sensor on the board like the [SS39ET](https://www.digikey.com/en/products/detail/honeywell-sensing-and-productivity-solutions/SS39ET/2839676), and include a small magnet on both prints that actuate the switches. 

This change requires:
-feeder PCB update
-feeder BOM update
-feeder CAD update
-feeder firmware update

**Comment by G-Pereira** [comment]
Done!
