### ISSUE TITLE
Switch all Frame CAD to FreeCAD

### ISSUE THREAD

**Issue by sphawes** [sphawes/index#52]
All CAD for the Index frame is currently done in Fusion 360. All CAD should be switched over to FreeCAD so that:
- it is more easily tracked using git
- it allows for proper PRs
- it uses open source software that is supported cross-platform

**Comment by Rendman** [comment]
I am currently working to modify the FreeCAD models to account for the FreeCAD naming topology problem.

**Comment by G-Pereira** [comment]
Done!
