### ISSUE TITLE
Feeder film tension arm interferes with Z gantry when down cam inspects feeder

### ISSUE THREAD

**Issue by sphawes** [sphawes/index#60]
When the X gantry moves over a feeder so that the down camera can see the part ready to be picked, the Z gantries protrude far enough that they can interfere with the feeder's film tension arm.

The film tension assembly needs to be edited so that it does not stick up so far from the top of the feeder, or (preferably) so that it sits much farther back, and the Z gantries have no chance of interfering.

**Comment by G-Pereira** [comment]
This has been fixed!
