### ISSUE TITLE
[Mobo] IRF540N MOSFETs can not be operated directly with 3.3V MCU output

### ISSUE THREAD

**Issue by kiesel-electronics** [sphawes/index#69]
The IRF540N isn't a logic level MOSFET. To fully switch on, it requires about 10V at it's gate.
If driven by a 3.3V MCU output, it doesn't switch on reliably and may heat up significantly.
For reliable operation, a gate driver circuit with appropriate supply voltage is required.

**Comment by g2pmas** [comment]
I use AOD4184A (very cheap on LCSC) or KIA30N06BD (LCSC PN: C134931). Often i add flyback diode, status led and a fuse.
![immagine](https://user-images.githubusercontent.com/28573205/102649976-6e6e6700-416a-11eb-9595-b00fb9b5e1c0.png)

**Comment by kiesel-electronics** [comment]
Yes, those have a threshold voltage of max. 2.5V.
But still, they don't switch on fully with 3.3V. As you can see in the diagram "On-Region Characteristics" (AOD4184A), the transistor will limit the current to something between 20A and 40A.
I guess there is no use case for such high currents in this kind of PnP machine anyway, so this won't be a significant issue.
With 35um copper PCBs anything beyond 10A is also pretty impractical, because of the huge trace width required.

Probably this kind of transistor is simply overkill and much smaller ones would do fine.

**Comment by sphawes** [comment]
Sorry folks, that footprint is incorrect! The mosfet I ended up getting working on this board was [this one](https://lcsc.com/product-detail/MOSFET_Wuxi-NCE-Power-Semiconductor-NCE6020AK_C108639.html). Not easily found on Digikey though. Looking at the TSM900 as a replacement. Max gate threshold voltage is 2.5v, should be able to be triggered with a 3.3V GPIO just fine. I need to update the symbol to fix the naming, if the TMS900 seems like a good option.

**Comment by kiesel-electronics** [comment]
![grafik](https://user-images.githubusercontent.com/57568035/102725840-17a78f80-431a-11eb-94ea-1b9ab262c4e7.png)
That is still a bit close for my taste, at 3V it's doing almost nothing.
I would recommend to put in some level shifting to 5V, just to be sure.
Something like https://www.mouser.de/datasheet/2/308/MC74VHC1G125_D-1387542.pdf should do fine.

**Comment by kiesel-electronics** [comment]
For the TMS900, I'm not sure. The datasheet doesn't tell us RDS(on) for anything below 4.5V, so I would geuss, it is not really on below that.

**Comment by gasmeter** [comment]
Hi The FET needs to be turned hard on and quite quickly.
If low speed then a small fet can be used as a level shifter or better still a proper fet driver from someone like maxim.
Something like a max4426 series.
Peter

**Comment by kiesel-electronics** [comment]
@gasmeter Yes, it would be best, to use a dedicated MOSFET driver for switching.
The maxim parts are a bit expensive. Something like the FAN3100TSX should also do.
If the board should run on more than 12V, a dedicated power rail may be required.

Since we are not doing anything like PWM, switching loss shouldn't be much of an issue.
Ground lift is always an issue with power circuits. Careful design of the ground plane is required. Driving the gate with 10V would make this also more robust.

TPL7407LPWR isn't really meant as gate driver. For some odd reason, Mouser puts it in this category.
It is a nice replacement of the famous ULN2003. Toshiba makes something similar (TBD62083A).
With a pull up resistor it could be used as gate driver, but switch on wouldn't be very fast. 
Also, the signal is inverted. 
I would avoid a solution like this, because if the MCU is in reset for whatever reason, or the 3.3V rails fails, all power outputs may get switched on.

**Comment by gasmeter** [comment]
Hi
This might work for you.

If the voltage rail is higher than 12V add a zener on the gate.

![LOW_COST_FET_DRIVE](https://user-images.githubusercontent.com/3692556/102873790-7d3e6d80-4439-11eb-8917-a64f297dc088.jpg)

Use either a multi package inverter or single gate versions etc.
The 50R in series with the gate stops oscillations at rf frequencies.
Peter

**Comment by kiesel-electronics** [comment]
@gasmeter The 74HC4049 requires a 5V supply. If that fails, the output clamping might pull it down anyway.

If a level shifter is used, something like this might also work:
![grafik](https://user-images.githubusercontent.com/57568035/102916358-b3a0da80-4483-11eb-8272-4ef97287b66f.png)
I have this from the Duet2 schematic.
The signal from the MCU is still inverted, but that shouldn't be an issue.
But if the 5V rail get's shorted, the issue is still the same...

**Comment by gasmeter** [comment]
I agree something along those lines 

I think it would make sense to generate a supply OK signal for the entire board.
Take the various supplies etc and any critical signals and produce a signal that can be used as an interlock.

Example using the interlock signal.

![power_fet_protection](https://user-images.githubusercontent.com/3692556/102981726-4d5a9d00-4501-11eb-95c8-dd02bab15524.jpg)

Peter

**Comment by kiesel-electronics** [comment]
I made a little schematic, how the power good signal could be created.
The LM339 is a quad opamp with open collector outputs and a max supply voltage of 36V.
![grafik](https://user-images.githubusercontent.com/57568035/103025763-c46c5180-4552-11eb-9053-a51f48fd1f09.png)
First, I create a 2.5V reference voltage. I use a zener and a resistor here, but any method would do.
Then an opamp is used to compare 3.3V against the reference. The same is done for 5V, but with a voltage divider in the front.
More voltage rails could be observed like this. The outputs are connected together and pulled up by a 10k resistor (wired AND).
The fault should be the dominant case, so positive logic must be used. 
Last, I (mis)use a opamp as inverter to generate the nPowerGood signal we want.
Because the whole circuit is driven by the rail, which is switching the MOSFET, nothing would happen, if this rail fails.

**Comment by kiesel-electronics** [comment]
@gasmeter I think, the 74HC4049 wouldn't work well with 3.3V signal input (if used with 5V Vcc), because VIH (input high threshold) is already 3.15V at 4.5V Vcc.

Parts from the HCT or AHCT (the T is important) logic series have a fixed VIH at 2V. So 74HCT04 should work fine.

**Comment by G-Pereira** [comment]
This issue was discussed on Discord and in order to keep BOM cost low, a MOSFET with signal-level gate characteristics was preferred and PR #78 addressed this issue
