### ISSUE TITLE
Add KiCad cache and bak files to .gitignore

### ISSUE THREAD

**Issue by NightSkySK** [sphawes/index#7]
I'm not an expert about KiCad but I assume files like
pnp/pcb/mobo/fp-info-cache
pnp/pcb/mobo/*.sch-bak
pnp/pcb/mobo/*.kicad_pcb-bak
should be added to .gitignore and removed from repository?
Please refer to articles:
[Project and libary setup for sharing and collaboration](https://forum.kicad.info/t/project-and-libary-setup-for-sharing-and-collaboration/20842)
[fp-info-cache purpose](https://forum.kicad.info/t/fp-info-cache-purpose/16569)

Of course the same rules should apply to:
pnp/pcb/piggyback
feeder\pcb\feederFloor
feeder\pcb\indexingWheel
feeder\pcb\mobo

**Comment by adlerweb** [comment]
Probably a good idea to just use common gitignore templates like https://www.gitignore.io/api/kicad

**Comment by NightSkySK** [comment]
@adlerweb yes, it seems to be the best idea.  The only thing that @sphawes need to consider if he want to keep Gerbers available (which may ends like in issue #8 ) or like the templete suggest to exclude gereber folders 

``` 
# Gerber export output
out/
```

**Comment by sphawes** [comment]
Thanks @NightSkySK @adlerweb, I'll make sure to add those to my gitignore. I'm inclined to stop exporting the Gerber files to prevent things like [#8](https://github.com/sphawes/index/issues/8) as you said. Makes them a bit less accessible, but given that it's still heavily under development and likely buggy, I don't think that's a bad thing.

**Comment by sphawes** [comment]
Fixed with commit 701ddd6.

**Comment by adlerweb** [comment]
> Makes them a bit less accessible, but given that it's still heavily under development and likely buggy, I don't think that's a bad thing.
For the meantime, yes. I would suggest to tag the repo and attach gerbers as "Pre-Release" if you produce a prototype for a video. This way people could access gerbers and create boards as shown and easily compare to current HEAD.
