### ISSUE TITLE
[Mobo] POWER MOSFETs are not protected by flyback diodes

### ISSUE THREAD

**Issue by kiesel-electronics** [sphawes/index#70]
If a inductive load, like a solenoid or a motor get's driven by the MOSFETs, there may occur significant voltage spikes when the load is switched off.
Adding a flyback diode would be an easy way to protect the MOSFETs.
Another way would be adding a clamping circuit to limit the voltage overshoot.
Also a power switch with integrated active clamping could be used.

**Comment by G-Pereira** [comment]
This is a really good idea! I can work on this but we need to merge #74 first
