### ISSUE TITLE
List of current features and deficiencies needed for Beta/Stable?

### ISSUE THREAD

**Issue by muramasatheninja** [sphawes/index#73]
I've been really excited to follow this project and am hoping to build one soon. One thing I'm trying to figure out is what is needed to get this project to a somewhat stable point where people like me can jump on. I can see attempting to build one of these, but am curious what to expect at this point. 

Maybe a list of issues that needs to be accomplished so some of can jump in?

**Comment by sphawes** [comment]
Hey @muramasatheninja!

All of the issues with the Index are being tracked here, in Github! The current open issues effectively outline everything that needs to be fixed before recommending that folks build one to do actual work. If you'd like to contribute to getting us there, poking through the issues and filing a PR with a fix after reading the Wiki would be the best way to do so!

You can read a bit more about when this happens in the [FAQ](https://github.com/sphawes/index/wiki/FAQ). When we get to that 2.0 release, I'll be sure to be pretty vocal about it so if you're following the project you'll know!
