### ISSUE TITLE
piggyback Gerber REV000 should not be used

### ISSUE THREAD

**Issue by NightSkySK** [sphawes/index#8]
The Gergber files for piggyback in REV000 folder are affected by problems which are described in [Controlling 30 PnP Feeders! video](https://youtu.be/pKZi71ofzjw)
**Should not be used for fabrication any more.**

If I'm not wrong the board at piggyback.kicad_pcb is already updated with fixes.

**Comment by sphawes** [comment]
This was fixed in commit 701ddd6 by removing all fabrication outputs.
