### ISSUE TITLE
machine.xml file

### ISSUE THREAD

**Issue by JudgeBeeb** [sphawes/index#83]
It would be helpful (for n00bs like me) to include a known working OpenPNP 'machine.xml' file in the 'code' folder of the 'mobo-rev02' branch.

**Comment by G-Pereira** [comment]
Definitely agree @JudgeBeeb  . Do you have an idea who has the most complete configuration of OpenPnP v2? @sphawes ?

**Comment by G-Pereira** [comment]
Duplicate of #10 which has more information.
