### ISSUE TITLE
[MOBO] Fix schematic symbols and values

### ISSUE THREAD

**Issue by G-Pereira** [sphawes/index#85]
- There are LEDs with different symbols although they are the same. This leads to separate groups of components.
- Replace resistor value with 10k for 10K
- Swap CFG headers for male
- Change silkscreen to REV03
- Update footprints (which include 3D models)
- Change USB connector symbol to a dual unit
- Change silkscreen to REV03-Beta
- Set PCB grid origin to be able to open the board on FreeCAD with [KiCAD StepUp](https://github.com/easyw/kicadStepUpMod/)

**Comment by sphawes** [comment]
Super clean!! Thanks! That adjustment for KiCAD StepUp is going to be great!

**Comment by G-Pereira** [comment]
Merged!
